config/routes.rb
Rails.application.routes.draw do
  
  root 'todos#index'

  get 'todo/:id', to: 'todos#show', as: 'todo_show'
  get 'todo', to:'todos#new'
  get 'edit_todo/:id', to: 'todos#edit', as: 'edit_todo'

  post 'todo', to: 'todos#create'

  patch 'todo', to: 'todos#update'

  delete 'todo/:id', to: 'todos#destroy', as: 'delete_todo'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  
  def index
    @todos = Todo.all 
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todo_show_path(@todo)
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:format])
    if @todo.update(todo_params)
      redirect_to todo_show_path(@todo)
    else
      render :edit
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to root_path 
  end

  private
     def todo_params
      params.require(:todo).permit(:item, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>
  Editing: <%= @todo.item %>
</h1>

<%= form_for @todo do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item %>

  <br />

  <%= f.label :description %>
  <%= f.text_field :description %>

  <br />

  <%= f.submit %>
<% end %>

<%= link_to 'Back', todo_show_path(@todo) %>

app/views/todos/index.html.erb
<h1>ToDo List</h1>

  <ul>
    <% @todos.each do |todo| %>

      <li> 
        <%= link_to todo.item, todo_show_path(todo) %> 
      </li>

    <% end %>
  </ul>

  <%= link_to 'New ToDo Item', todo_path %>

app/views/todos/new.html.erb
<h1>Create a ToDo Item</h1>

<%= form_for @todo do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item %>

  <br />
  
  <%= f.label :description %>
  <%= f.text_field :description %>

  <br />

  <%= f.submit %>
<% end %>

<%= link_to 'Home', root_path %>

app/views/todos/show.html.erb
<h1>Your ToDo list is:</h1>

<i>
  Item: <%= @todo.item %> 
</i>

<i>
  Posted At: <%= @todo.created_at %> 
</i>

<p> 
  <%= @todo.description %> 
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %>
<%= link_to 'Delete', delete_todo_path(@todo), method: :delete, data: {confirm: 'Really Delete?'} %>

<%= link_to 'Home', root_path %>